[unstable]
unstable-options = true

[build]
out-dir = "../install/bin"


[env]
DUST_Z3_PATH="/home/chanheec/local_bin/z3"
DYLD_LIBRARY_PATH="../install/lib/rustlib/x86_64-apple-darwin/lib" 
LD_LIBRARY_PATH="../install/lib" 
