[unstable]
unstable-options = true

[build]
out-dir = "../install/bin"
rustc = "../install/bin/rustc"



[env]
DUST_Z3_PATH="~/local_bin_z3" 
DYLD_LIBRARY_PATH="../install/lib/rustlib/x86_64-apple-darwin/lib" 
LD_LIBRARY_PATH="../install/lib" 
