name: build and upload file

# possible way -> take argument asking whether you want to compile rust or not 

on: [push]

jobs:
  build_and_save:
    runs-on: [self-hosted, linux]       #ubuntu-20.04     # ubuntu-latest  is same with  # ubuntu-20.04   
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: build dist
        run: |
          python write_file.py

      - name: upload artifacts via github action
        uses: actions/upload-artifact@v2
        with:
          name: demo-folder
          path: |
            demofolder


      # - name: upload artifacts to designated place on server
      #   run: upload-artifacts.sh
