name: build and upload file

# possible way -> take argument asking whether you want to compile rust or not 

on: [push]

jobs:
  build_and_save:
    runs-on: [self-hosted, linux]       
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: running cargo test
        working-directory: ./verify      # not will be used if we use a separate repo
        run: |
          ln -sf ~/local_bin/install ../install
          ../install/bin/rustc --version
          RUSTC=../install/bin/rustc ../install/bin/cargo build
          RUSTC=../install/bin/rustc RUSTDOC=../install/bin/rustdoc  ../install/bin/cargo test




